Test ng hw
ozb1coco/TAF_AQA18_onl pull request #1
Opened 2022-12-03 23:17 UTC by ozb1coco

2022-12-13 09:28 UTC, wildpioneer requested changes

2022-12-13 09:28 UTC, wildpioneer commented on src/test/java/tests/testNG_HW/CalculatorTest.java
> +
Отсутствуют тесты на:
1. enable
2. description
3. invocationCount, invocationTimeOut, threadPoolSize
4. timeOut
5. dataProvider
6. dependsOnMethods
7. groups
8. @Parameters
9. priority
10. retryAnalyzer
11. Double.NaN
12. Double.NEGATIVE_INFINITY
13. Double.POSITIVE_INFINITY

2022-12-19 18:16 UTC, ozb1coco commented on src/test/java/tests/testNG_HW/CalculatorTest.java
> +
Исправлено.

2022-12-20 07:07 UTC, wildpioneer commented
Проверено

2022-12-20 07:07 UTC, closed without merging