Selenium wd hw
ozb1coco/TAF_AQA18_onl pull request #4
Opened 2022-12-10 08:27 UTC by ozb1coco

homework selenium

2022-12-13 09:45 UTC, wildpioneer requested changes

2022-12-13 09:45 UTC, wildpioneer commented on src/test/java/tests/SmokeTest.java
> +        driver.get("https://kermi-fko.ru/raschety/Calc-Rehau-Solelec.aspx");
Форматирование. Необходимо разделять логические части пустыми строками, чтобы было комфортнее читать

2022-12-19 18:23 UTC, ozb1coco commented on src/test/java/tests/SmokeTest.java
> +        driver.get("https://kermi-fko.ru/raschety/Calc-Rehau-Solelec.aspx");
Исправлено.

2022-12-20 07:02 UTC, wildpioneer commented
Проверено

2022-12-20 07:02 UTC, closed without merging